<script setup lang="ts">
import { PlatformClient, type PlatformCashOverview, type PlatformInventoryPurchase, type PlatformInventorySupplier, type PlatformSalesReport, type WorkshopOrder } from '@stelfaro/api-client';
import { UiButton, UiCard, UiInput, UiModalShell, UiSelect, UiStatusBadge, UiTextarea } from '@stelfaro/ui';
import { ArrowDownLeft, ArrowUpRight, Banknote, CalendarRange, CircleDollarSign, LockKeyhole, Plus, RefreshCw, Scale } from 'lucide-vue-next';
import { computed, onMounted, reactive, ref, watch } from 'vue';
import BillingFloatingToastStack from '../components/BillingFloatingToastStack.vue';

const props = withDefaults(defineProps<{ platformBaseUrl?: string; authToken?: string|null; tenantId: number; workshopEnabled?: boolean }>(), { platformBaseUrl: '/api/v1', authToken: null, workshopEnabled: false });
const client = computed(() => new PlatformClient(props.platformBaseUrl, { authToken: props.authToken }));
const tab = ref<'cash'|'sales'>('cash'); const loading = ref(false); const overview = ref<PlatformCashOverview|null>(null); const report = ref<PlatformSalesReport|null>(null); const toasts = ref<any[]>([]);
const selectedRegisterId = ref('');
const modal = ref<'open'|'movement'|'close'|'reconcile'|null>(null); const suppliers = ref<PlatformInventorySupplier[]>([]); const orders = ref<WorkshopOrder[]>([]); const purchases = ref<PlatformInventoryPurchase[]>([]); const reconcilingExpenseId = ref<number|null>(null); const selectedPurchaseId = ref('');
const closeTargetId = ref<number|null>(null);
const openForm = reactive({ opening_balance: 0, name: 'Caja principal', notes: '' });
const movementForm = reactive({ direction: 'out', kind: 'supplier_purchase', method: 'cash', amount: 0, description: '', reference: '', supplier_id: '', workshop_order_id: '', expense_category: 'replacement', destination: 'direct_order' });
const closeForm = reactive({ declared_balance: 0, notes: '' });
const salesFilters = reactive({ date_from: new Date(new Date().getFullYear(), new Date().getMonth(), 1).toISOString().slice(0, 10), date_to: new Date().toISOString().slice(0, 10), source_type: '', payment_status: '' });
const money = (value: number) => new Intl.NumberFormat('es-SV', { style: 'currency', currency: 'USD' }).format(value || 0);
const dateTime = (value: string) => new Intl.DateTimeFormat('es-SV', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value));
const balance = computed(() => overview.value?.active_session?.expected ?? 0);
const closingExpected = computed(() => closeTargetId.value ? (overview.value?.pending_counts.find(item => item.id === closeTargetId.value)?.expected ?? overview.value?.active_session?.expected ?? 0) : balance.value);
const methodOptions = [{ value: 'cash', label: 'Efectivo' }, { value: 'card', label: 'Tarjeta' }, { value: 'transfer', label: 'Transferencia' }, { value: 'other', label: 'Otro' }];
const supplierOptions = computed(() => [{ value: '', label: 'Sin proveedor registrado' }, ...suppliers.value.map(item => ({ value: String(item.id), label: item.name }))]);
const orderOptions = computed(() => [{ value: '', label: 'No asociar a una orden' }, ...orders.value.map(item => ({ value: String(item.id), label: `${item.ticket} · ${item.customer.name} · ${item.device.brand} ${item.device.model}` }))]);
const categoryOptions = [{ value: 'replacement', label: 'Repuesto' }, { value: 'tool', label: 'Herramienta' }, { value: 'service', label: 'Servicio' }, { value: 'transport', label: 'Transporte' }, { value: 'general', label: 'Gasto general' }];
const destinationOptions = [{ value: 'direct_order', label: 'Uso directo en orden' }, { value: 'inventory', label: 'Ingresará a inventario' }, { value: 'expense', label: 'Gasto operativo' }];
const sourceOptions = [{ value: '', label: 'Todos los orígenes' }, { value: 'dte', label: 'Facturación' }, { value: 'workshop_order', label: 'Taller' }];
const paymentOptions = [{ value: '', label: 'Todos los cobros' }, { value: 'paid', label: 'Cobrado' }, { value: 'receivable', label: 'Pendiente de cobro' }];
const purchaseOptions = computed(() => [{ value: '', label: 'Selecciona la compra importada' }, ...purchases.value.map(item => ({ value: String(item.id), label: `${item.document_number || `Compra #${item.purchase_number}`} · ${money(Number(item.total))} · ${item.supplier?.name || 'Proveedor'}` }))]);
const registerOptions = computed(() => (overview.value?.registers || []).map(register => ({ value: String(register.id), label: `${register.branch_code ? `${register.branch_code} · ` : ''}${register.branch_name || register.name}` })));
const selectedRegister = computed(() => overview.value?.registers.find(register => String(register.id) === selectedRegisterId.value) ?? null);

function notify(title: string, message = '', variant = 'success') { const id = `${Date.now()}-${Math.random()}`; toasts.value.push({ id, title, message, variant }); window.setTimeout(() => { toasts.value = toasts.value.filter(item => item.id !== id); }, 4300); }
function errorMessage(error: any) { return error?.response?.message || error?.message || 'Revisa los datos e intenta nuevamente.'; }
async function loadCash() { loading.value = true; try { let result = await client.value.cashOverview(props.tenantId, selectedRegisterId.value ? { cash_register_id: Number(selectedRegisterId.value) } : {}); if (!selectedRegisterId.value && result.registers[0]) { selectedRegisterId.value=String(result.registers[0].id); result=await client.value.cashOverview(props.tenantId, { cash_register_id:Number(selectedRegisterId.value) }); } overview.value = result; } catch (error) { notify('No pudimos cargar Caja', errorMessage(error), 'error'); } finally { loading.value = false; } }
async function loadReport() { loading.value = true; try { report.value = await client.value.commercialSalesReport(props.tenantId, { ...salesFilters, core_sucursal_id: selectedRegister.value?.branch_id || undefined }); } catch (error) { notify('No pudimos cargar las ventas', errorMessage(error), 'error'); } finally { loading.value = false; } }
async function loadRelations() { try { suppliers.value = (await client.value.inventorySuppliers(props.tenantId, { status: 'active', per_page: 100 })).data; purchases.value = (await client.value.inventoryPurchases(props.tenantId, { per_page: 100 })).data; if (props.workshopEnabled) orders.value = (await client.value.workshopOrders(props.tenantId, { per_page: 100 })).data; } catch { /* Los selectores pueden seguir vacíos. */ } }
async function openSession() { loading.value = true; try { await client.value.openCashSession(props.tenantId, { ...openForm, cash_register_id: selectedRegisterId.value ? Number(selectedRegisterId.value) : undefined }); modal.value = null; notify('Caja abierta', 'Ya puedes registrar cobros y salidas en efectivo.'); await loadCash(); } catch (error) { notify('No se pudo abrir', errorMessage(error), 'error'); } finally { loading.value = false; } }
async function closeSession() { const sessionId=closeTargetId.value || overview.value?.active_session?.id; if (!sessionId) return; loading.value = true; try { const response = await client.value.closeCashSession(props.tenantId, sessionId, closeForm); modal.value = null; closeTargetId.value=null; notify('Caja cerrada', response.data.difference === 0 ? 'El efectivo quedó cuadrado.' : `Diferencia registrada: ${money(response.data.difference || 0)}.`, response.data.difference === 0 ? 'success' : 'warning'); await loadCash(); } catch (error) { notify('No se pudo cerrar', errorMessage(error), 'error'); } finally { loading.value = false; } }
function openCount(session:any) { closeTargetId.value=session.id; closeForm.declared_balance=session.expected; modal.value='close'; }
async function saveMovement() { loading.value = true; try { await client.value.createCashMovement(props.tenantId, { ...movementForm, cash_register_id: selectedRegisterId.value ? Number(selectedRegisterId.value) : null, supplier_id: movementForm.supplier_id || null, workshop_order_id: movementForm.workshop_order_id || null, idempotency_key: crypto.randomUUID?.() || `${Date.now()}` }); modal.value = null; notify(movementForm.direction === 'out' ? 'Salida registrada' : 'Ingreso registrado', movementForm.workshop_order_id ? 'El movimiento quedó relacionado con la orden.' : 'Caja fue actualizada.'); Object.assign(movementForm, { direction: 'out', kind: 'supplier_purchase', method: 'cash', amount: 0, description: '', reference: '', supplier_id: '', workshop_order_id: '', expense_category: 'replacement', destination: 'direct_order' }); await loadCash(); } catch (error) { notify('No se pudo registrar', errorMessage(error), 'error'); } finally { loading.value = false; } }
function newMovement(direction: 'in'|'out') { movementForm.direction = direction; movementForm.kind = direction === 'in' ? 'manual_income' : 'supplier_purchase'; modal.value = 'movement'; }
function openReconcile(expenseId: number) { reconcilingExpenseId.value = expenseId; selectedPurchaseId.value = ''; modal.value = 'reconcile'; }
async function reconcileExpense() { if (!reconcilingExpenseId.value || !selectedPurchaseId.value) return; loading.value = true; try { const result = await client.value.reconcileCashExpense(props.tenantId, reconcilingExpenseId.value, Number(selectedPurchaseId.value)); modal.value = null; notify(result.data.status === 'reconciled' ? 'Compra conciliada' : 'Diferencia por revisar', result.data.difference === 0 ? 'El DTE quedó asociado sin duplicar la salida.' : `La diferencia es ${money(result.data.difference)}.`, result.data.difference === 0 ? 'success' : 'warning'); await Promise.all([loadCash(), loadRelations()]); } catch (error) { notify('No se pudo conciliar', errorMessage(error), 'error'); } finally { loading.value = false; } }
watch(tab, value => { if (value === 'sales' && !report.value) void loadReport(); });
watch(selectedRegisterId, () => { if (overview.value) void (tab.value === 'cash' ? loadCash() : loadReport()); });
onMounted(() => { void Promise.all([loadCash(), loadRelations()]); });
</script>

<template>
  <div class="space-y-5">
    <BillingFloatingToastStack :toasts="toasts" />
    <section class="flex flex-col gap-4 rounded-xl border border-primary/20 bg-gradient-to-r from-primary-soft to-surface p-5 sm:flex-row sm:items-center sm:justify-between">
      <div><p class="text-sm font-semibold uppercase tracking-wide text-primary">Control financiero</p><h2 class="mt-1 text-2xl font-bold text-text">Caja y ventas</h2><p class="mt-1 text-sm text-muted">El dinero real se controla aquí; Taller e inventario se conectan sin duplicar movimientos.</p></div>
      <div class="flex flex-wrap items-end gap-2"><UiSelect v-if="registerOptions.length" v-model="selectedRegisterId" class="min-w-56" label="Sucursal / caja" hide-label :options="registerOptions" /><UiButton variant="secondary" @click="tab = 'cash'"><Banknote class="h-4 w-4" />Caja</UiButton><UiButton variant="secondary" @click="tab = 'sales'"><CalendarRange class="h-4 w-4" />Ventas</UiButton><UiButton variant="ghost" :disabled="loading" aria-label="Actualizar" @click="tab === 'cash' ? loadCash() : loadReport()"><RefreshCw class="h-4 w-4" :class="loading ? 'animate-spin' : ''" /></UiButton></div>
    </section>

    <template v-if="tab === 'cash'">
      <UiCard v-for="pending in overview?.pending_counts || []" :key="`pending-${pending.id}`" class="border-warning/30 bg-warning-soft"><div class="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><UiStatusBadge tone="warning">Conteo pendiente</UiStatusBadge><p class="mt-2 font-semibold text-text">{{ pending.register.name }} · {{ pending.business_date }}</p><p class="text-sm text-muted">El corte automático esperaba {{ money(pending.expected) }}.</p></div><UiButton variant="secondary" @click="openCount(pending)">Confirmar efectivo</UiButton></div></UiCard>
      <UiCard v-if="overview?.active_session" class="border-primary/30">
        <div class="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><div class="flex items-center gap-2"><UiStatusBadge :tone="overview.active_session.status === 'open' ? 'success' : 'warning'">{{ overview.active_session.status === 'open' ? 'Caja abierta' : 'Conteo pendiente' }}</UiStatusBadge><span class="text-sm text-muted">{{ overview.active_session.register.name }}</span></div><p class="mt-3 text-3xl font-bold text-text">{{ money(balance) }}</p><p class="text-sm text-muted">Efectivo esperado · {{ overview.active_session.status === 'open' ? `abierta ${dateTime(overview.active_session.opened_at)}` : 'confirma el efectivo físico' }}</p></div><div class="flex flex-wrap gap-2"><template v-if="overview.active_session.status === 'open'"><UiButton @click="newMovement('in')"><ArrowDownLeft class="h-4 w-4" />Ingreso</UiButton><UiButton variant="secondary" @click="newMovement('out')"><ArrowUpRight class="h-4 w-4" />Salida</UiButton></template><UiButton variant="ghost" @click="openCount(overview.active_session)"><LockKeyhole class="h-4 w-4" />{{ overview.active_session.status === 'open' ? 'Cerrar caja' : 'Confirmar conteo' }}</UiButton></div></div>
      </UiCard>
      <UiCard v-else><div class="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><h3 class="font-semibold text-text">La caja está cerrada</h3><p class="mt-1 text-sm text-muted">Registra el efectivo inicial para comenzar a cobrar y pagar desde esta terminal.</p></div><UiButton @click="modal = 'open'"><Plus class="h-4 w-4" />Abrir caja</UiButton></div></UiCard>

      <section class="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
        <UiCard><p class="text-sm text-muted">Ingresos</p><p class="mt-2 text-2xl font-bold text-success">{{ money(overview?.summary.inflows || 0) }}</p></UiCard>
        <UiCard><p class="text-sm text-muted">Salidas</p><p class="mt-2 text-2xl font-bold text-danger">{{ money(overview?.summary.outflows || 0) }}</p></UiCard>
        <UiCard><p class="text-sm text-muted">Por documentar</p><p class="mt-2 text-2xl font-bold text-warning">{{ overview?.summary.pending_documents || 0 }}</p><p class="text-xs text-muted">Compras o gastos sin DTE conciliado</p></UiCard>
        <UiCard><p class="text-sm text-muted">Movimiento neto</p><p class="mt-2 text-2xl font-bold text-text">{{ money((overview?.summary.inflows || 0) - (overview?.summary.outflows || 0)) }}</p></UiCard>
      </section>

      <UiCard class="overflow-hidden p-0"><div class="border-b border-line px-5 py-4"><h3 class="font-semibold text-text">Movimientos recientes</h3></div><div v-if="overview?.data.length" class="divide-y divide-line"><div v-for="item in overview.data" :key="item.id" class="flex items-center gap-3 px-5 py-4 transition hover:bg-surface-muted"><span class="rounded-lg p-2" :class="item.direction === 'in' ? 'bg-success-soft text-success' : 'bg-danger-soft text-danger'"><ArrowDownLeft v-if="item.direction === 'in'" class="h-4 w-4" /><ArrowUpRight v-else class="h-4 w-4" /></span><div class="min-w-0 flex-1"><p class="truncate font-semibold text-text">{{ item.description }}</p><p class="mt-0.5 text-xs text-muted">{{ dateTime(item.occurred_at) }} · {{ methodOptions.find(option => option.value === item.method)?.label || item.method }}<span v-if="item.order"> · {{ item.order.ticket }}</span></p></div><div class="flex items-center gap-3 text-right"><UiButton v-if="item.expense?.status === 'pending_document'" variant="ghost" size="sm" @click="openReconcile(item.expense.id)">Conciliar DTE</UiButton><div><p class="font-bold" :class="item.direction === 'in' ? 'text-success' : 'text-danger'">{{ item.direction === 'in' ? '+' : '-' }}{{ money(item.amount) }}</p><UiStatusBadge v-if="item.expense?.status === 'pending_document'" tone="warning">Sin DTE</UiStatusBadge><UiStatusBadge v-else-if="item.expense?.status === 'reconciled'" tone="success">Conciliado</UiStatusBadge></div></div></div></div><p v-else class="px-5 py-12 text-center text-sm text-muted">Todavía no hay movimientos registrados.</p></UiCard>
    </template>

    <template v-else>
      <UiCard><div class="grid gap-3 md:grid-cols-4"><UiInput v-model="salesFilters.date_from" type="date" label="Desde" /><UiInput v-model="salesFilters.date_to" type="date" label="Hasta" /><UiSelect v-model="salesFilters.source_type" label="Origen" :options="sourceOptions" /><UiSelect v-model="salesFilters.payment_status" label="Cobro" :options="paymentOptions" /></div><div class="mt-4 flex justify-end"><UiButton @click="loadReport">Actualizar reporte</UiButton></div></UiCard>
      <section class="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><UiCard><CircleDollarSign class="h-5 w-5 text-primary" /><p class="mt-2 text-xs text-muted">Total vendido</p><p class="text-xl font-bold text-text">{{ money(report?.summary.total || 0) }}</p></UiCard><UiCard><p class="text-xs text-muted">Neto</p><p class="mt-2 text-xl font-bold text-text">{{ money(report?.summary.net || 0) }}</p></UiCard><UiCard><p class="text-xs text-muted">IVA</p><p class="mt-2 text-xl font-bold text-text">{{ money(report?.summary.tax || 0) }}</p></UiCard><UiCard><p class="text-xs text-muted">Costo</p><p class="mt-2 text-xl font-bold text-text">{{ money(report?.summary.cost || 0) }}</p></UiCard><UiCard><Scale class="h-5 w-5 text-success" /><p class="mt-2 text-xs text-muted">Margen</p><p class="text-xl font-bold text-success">{{ money(report?.summary.margin || 0) }}</p></UiCard></section>
      <UiCard class="overflow-hidden p-0"><div class="overflow-x-auto"><table class="min-w-full text-sm"><thead class="bg-surface-muted text-left text-xs uppercase text-muted"><tr><th class="px-5 py-3">Fecha</th><th class="px-5 py-3">Venta</th><th class="px-5 py-3">Cliente</th><th class="px-5 py-3">Estado</th><th class="px-5 py-3 text-right">Total</th></tr></thead><tbody class="divide-y divide-line"><tr v-for="sale in report?.data || []" :key="sale.id" class="transition hover:bg-surface-muted"><td class="px-5 py-4 text-muted">{{ sale.date }}</td><td class="px-5 py-4"><p class="font-semibold text-text">{{ sale.source_number || `Venta #${sale.id}` }}</p><p class="text-xs text-muted">{{ sale.source_type === 'workshop_order' ? 'Taller' : `DTE ${sale.document_type || ''}` }}</p></td><td class="px-5 py-4 text-text">{{ sale.customer_name || 'Consumidor final' }}</td><td class="px-5 py-4"><UiStatusBadge :tone="sale.payment_status === 'receivable' ? 'warning' : 'success'">{{ sale.payment_status === 'receivable' ? 'Por cobrar' : 'Cobrado' }}</UiStatusBadge></td><td class="px-5 py-4 text-right font-bold text-text">{{ money(sale.total) }}</td></tr><tr v-if="!report?.data.length"><td colspan="5" class="px-5 py-12 text-center text-muted">No hay ventas en este período.</td></tr></tbody></table></div></UiCard>
    </template>

    <UiModalShell :open="modal === 'open'" title="Abrir caja" description="Indica cuánto efectivo hay antes del primer movimiento." @close="modal = null"><div class="space-y-4"><UiInput v-model.number="openForm.opening_balance" type="number" min="0" step="0.01" label="Efectivo inicial" suffix="USD" /><UiInput v-model="openForm.name" label="Nombre de la caja" /><UiTextarea v-model="openForm.notes" label="Nota opcional" /></div><template #footer><UiButton variant="ghost" @click="modal = null">Cancelar</UiButton><UiButton :disabled="loading" @click="openSession">Abrir caja</UiButton></template></UiModalShell>
    <UiModalShell :open="modal === 'close'" title="Cerrar caja" :description="`El sistema espera ${money(closingExpected)} en efectivo.`" @close="modal = null; closeTargetId = null"><div class="space-y-4"><UiInput v-model.number="closeForm.declared_balance" type="number" min="0" step="0.01" label="Efectivo contado" suffix="USD" /><UiTextarea v-model="closeForm.notes" label="Observación opcional" /></div><template #footer><UiButton variant="ghost" @click="modal = null; closeTargetId = null">Cancelar</UiButton><UiButton :disabled="loading" @click="closeSession">Cerrar y cuadrar</UiButton></template></UiModalShell>
    <UiModalShell :open="modal === 'movement'" :title="movementForm.direction === 'in' ? 'Registrar ingreso' : 'Registrar salida'" :description="movementForm.direction === 'out' ? 'Si es una compra, podrá conciliarse después con el DTE del proveedor.' : 'Registra dinero que realmente ingresó.'" @close="modal = null"><div class="grid gap-4 sm:grid-cols-2"><UiInput v-model.number="movementForm.amount" type="number" min="0.01" step="0.01" label="Monto" suffix="USD" /><UiSelect v-model="movementForm.method" label="Forma" :options="methodOptions" /><UiInput v-model="movementForm.description" class="sm:col-span-2" label="Concepto" placeholder="Ej. Pantalla para Samsung A54" /><template v-if="movementForm.direction === 'out'"><UiSelect v-model="movementForm.expense_category" label="Categoría" :options="categoryOptions" /><UiSelect v-model="movementForm.destination" label="Destino" :options="destinationOptions" /><UiSelect v-model="movementForm.supplier_id" label="Proveedor" :options="supplierOptions" /><UiSelect v-if="workshopEnabled" v-model="movementForm.workshop_order_id" label="Orden de taller" :options="orderOptions" /></template><UiInput v-model="movementForm.reference" class="sm:col-span-2" label="Referencia opcional" /></div><template #footer><UiButton variant="ghost" @click="modal = null">Cancelar</UiButton><UiButton :disabled="loading || movementForm.amount <= 0 || !movementForm.description" @click="saveMovement">Guardar movimiento</UiButton></template></UiModalShell>
    <UiModalShell :open="modal === 'reconcile'" title="Conciliar documento del proveedor" description="Selecciona la compra importada desde el JSON. La salida de caja no se repetirá." @close="modal = null"><UiSelect v-model="selectedPurchaseId" label="Compra recibida" :options="purchaseOptions" /><p v-if="purchases.length === 0" class="mt-3 text-sm text-muted">Primero importa el JSON desde Inventario → Compras.</p><template #footer><UiButton variant="ghost" @click="modal = null">Cancelar</UiButton><UiButton :disabled="loading || !selectedPurchaseId" @click="reconcileExpense">Conciliar</UiButton></template></UiModalShell>
  </div>
</template>
