<script setup lang="ts">
import { PlatformClient, type PlatformQuotation, type PlatformReceivable, type PlatformSalesOrder } from '@stelfaro/api-client';
import { UiButton, UiCard, UiInput, UiModalShell, UiSelect, UiStatusBadge, UiTextarea } from '@stelfaro/ui';
import { Banknote, ClipboardList, FileCheck2, FileText, Plus, ReceiptText, RefreshCw, Trash2 } from 'lucide-vue-next';
import { computed, onMounted, reactive, ref } from 'vue';
import BillingFloatingToastStack from '../components/BillingFloatingToastStack.vue';

const props = withDefaults(defineProps<{ platformBaseUrl?: string; authToken?: string|null; tenantId: number; appBaseUrl?: string }>(), { platformBaseUrl: '/api/v1', authToken: null, appBaseUrl: '/facturacion' });
const client = computed(() => new PlatformClient(props.platformBaseUrl, { authToken: props.authToken, credentials: 'include' }));
const tab = ref<'orders'|'quotes'|'receivables'>('orders');
const orders = ref<PlatformSalesOrder[]>([]);
const quotations = ref<PlatformQuotation[]>([]);
const receivables = ref<PlatformReceivable[]>([]);
const receivableTotal = ref(0);
const loading = ref(false);
const modal = ref<'order'|'quote'|'payment'|'cancel'|'convert'|null>(null);
const selectedOrder = ref<PlatformSalesOrder|null>(null);
const selectedQuotation = ref<PlatformQuotation|null>(null);
const toasts = ref<any[]>([]);
const line = () => ({ description: '', quantity: 1, unit_price: 0, discount_amount: 0 });
const orderForm = reactive({ title: '', customer_name: '', customer_phone: '', notes: '', deposit_amount: 0, deposit_method: 'cash', lines: [line()] });
const quoteForm = reactive({ title: '', customer_name: '', customer_phone: '', valid_until: '', requested_deposit: 0, terms: '', notes: '', lines: [line()] });
const paymentForm = reactive({ amount: 0, method: 'cash', reference: '' });
const cancelForm = reactive({ reason: '', retained_amount: 0, method: 'cash', reference: '' });
const methods = [{ value: 'cash', label: 'Efectivo' }, { value: 'card', label: 'Tarjeta' }, { value: 'transfer', label: 'Transferencia' }, { value: 'other', label: 'Otro' }];
const money = (value: number) => new Intl.NumberFormat('es-SV', { style: 'currency', currency: 'USD' }).format(value || 0);
const orderTotal = computed(() => orderForm.lines.reduce((sum, item) => sum + Math.max(0, item.quantity * item.unit_price - item.discount_amount), 0));
const quoteTotal = computed(() => quoteForm.lines.reduce((sum, item) => sum + Math.max(0, item.quantity * item.unit_price - item.discount_amount), 0));

function notify(title: string, message = '', variant = 'success') { const id = `${Date.now()}-${Math.random()}`; toasts.value.push({ id, title, message, variant }); window.setTimeout(() => { toasts.value = toasts.value.filter(item => item.id !== id); }, 4300); }
function errorMessage(error: any) { return error?.message || 'Revisa los datos e intenta nuevamente.'; }
async function load() { loading.value = true; try { const [orderResponse, quoteResponse, receivableResponse] = await Promise.all([client.value.salesOrders(props.tenantId, { per_page: 100 }), client.value.quotations(props.tenantId), client.value.receivables(props.tenantId)]); orders.value = orderResponse.data; quotations.value = quoteResponse.data; receivables.value = receivableResponse.data; receivableTotal.value = receivableResponse.summary.open; } catch (error) { notify('No pudimos cargar la operación', errorMessage(error), 'error'); } finally { loading.value = false; } }
function resetOrder() { Object.assign(orderForm, { title: '', customer_name: '', customer_phone: '', notes: '', deposit_amount: 0, deposit_method: 'cash', lines: [line()] }); modal.value = 'order'; }
function resetQuote() { Object.assign(quoteForm, { title: '', customer_name: '', customer_phone: '', valid_until: '', requested_deposit: 0, terms: '', notes: '', lines: [line()] }); modal.value = 'quote'; }
function addLine(target: 'order'|'quote') { (target === 'order' ? orderForm.lines : quoteForm.lines).push(line()); }
function removeLine(target: 'order'|'quote', index: number) { const lines = target === 'order' ? orderForm.lines : quoteForm.lines; if (lines.length > 1) lines.splice(index, 1); }
async function createOrder() { loading.value = true; try { await client.value.createSalesOrder(props.tenantId, { title: orderForm.title, customer: { name: orderForm.customer_name, phone: orderForm.customer_phone || null }, notes: orderForm.notes || null, lines: orderForm.lines, deposit: orderForm.deposit_amount > 0 ? { amount: orderForm.deposit_amount, method: orderForm.deposit_method } : undefined }); modal.value = null; notify('Orden creada', 'El anticipo y el saldo por cobrar quedaron vinculados.'); await load(); } catch (error) { notify('No se pudo crear', errorMessage(error), 'error'); } finally { loading.value = false; } }
async function createQuote() { loading.value = true; try { await client.value.createQuotation(props.tenantId, { title: quoteForm.title, customer: { name: quoteForm.customer_name, phone: quoteForm.customer_phone || null }, valid_until: quoteForm.valid_until || null, requested_deposit: quoteForm.requested_deposit, terms: quoteForm.terms || null, notes: quoteForm.notes || null, lines: quoteForm.lines }); modal.value = null; notify('Cotización creada', 'Puedes enviarla, aceptarla y convertirla en orden.'); await load(); } catch (error) { notify('No se pudo crear', errorMessage(error), 'error'); } finally { loading.value = false; } }
async function setOrderStatus(order: PlatformSalesOrder, status: string) { loading.value = true; try { await client.value.updateSalesOrder(props.tenantId, order.id, { status }); notify('Orden actualizada'); await load(); } catch (error) { notify('No se pudo actualizar', errorMessage(error), 'error'); } finally { loading.value = false; } }
function openPayment(order: PlatformSalesOrder) { selectedOrder.value = order; Object.assign(paymentForm, { amount: order.balance, method: 'cash', reference: '' }); modal.value = 'payment'; }
async function savePayment() { if (!selectedOrder.value) return; loading.value = true; try { await client.value.paySalesOrder(props.tenantId, selectedOrder.value.id, paymentForm); modal.value = null; notify('Pago registrado', 'Caja y cuenta por cobrar fueron actualizadas.'); await load(); } catch (error) { notify('No se pudo cobrar', errorMessage(error), 'error'); } finally { loading.value = false; } }
function openCancel(order: PlatformSalesOrder) { selectedOrder.value = order; Object.assign(cancelForm, { reason: '', retained_amount: 0, method: 'cash', reference: '' }); modal.value = 'cancel'; }
async function cancelOrder() { if (!selectedOrder.value) return; loading.value = true; try { await client.value.cancelSalesOrder(props.tenantId, selectedOrder.value.id, cancelForm); modal.value = null; notify('Orden cancelada', 'El saldo fue anulado y la devolución quedó registrada.'); await load(); } catch (error) { notify('No se pudo cancelar', errorMessage(error), 'error'); } finally { loading.value = false; } }
async function setQuoteStatus(quote: PlatformQuotation, status: string) { loading.value = true; try { await client.value.updateQuotationStatus(props.tenantId, quote.id, status); await load(); } catch (error) { notify('No se pudo actualizar', errorMessage(error), 'error'); } finally { loading.value = false; } }
function openConvert(quote: PlatformQuotation) { selectedQuotation.value = quote; Object.assign(paymentForm, { amount: quote.requested_deposit, method: 'cash', reference: '' }); modal.value = 'convert'; }
async function convertQuote() { if (!selectedQuotation.value) return; loading.value = true; try { const response = await client.value.convertQuotation(props.tenantId, selectedQuotation.value.id, { deposit: paymentForm.amount > 0 ? { amount: paymentForm.amount, method: paymentForm.method, reference: paymentForm.reference || null } : undefined }); modal.value = null; tab.value = 'orders'; notify('Orden creada', response.data.order_number); await load(); } catch (error) { notify('No se pudo convertir', errorMessage(error), 'error'); } finally { loading.value = false; } }
function invoiceHref(order: PlatformSalesOrder) {
  const base = props.appBaseUrl.replace(/\/$/, '');
  const billingBase = base.endsWith('/taller') ? `${base}/facturacion` : base;
  return `${billingBase}/fe?sales_order=${order.id}`;
}
function tone(status: string) { if (['settled','accepted','converted','delivered'].includes(status)) return 'success'; if (['cancelled','rejected'].includes(status)) return 'danger'; if (['partial','sent','ready'].includes(status)) return 'warning'; return 'info'; }
onMounted(load);
</script>

<template>
  <div class="space-y-4">
    <BillingFloatingToastStack :toasts="toasts" />
    <section class="rounded-xl border border-line bg-surface p-4 shadow-sm">
      <div class="flex items-center justify-between gap-3"><div><p class="text-xs font-bold uppercase tracking-wide text-primary">Operación comercial</p><h2 class="mt-1 text-xl font-bold text-text">Trabajos por encargo</h2><p class="mt-1 text-sm text-muted">Cotiza, recibe anticipos y controla lo pendiente sin duplicar la venta.</p></div><UiButton variant="ghost" :disabled="loading" aria-label="Actualizar" @click="load"><RefreshCw class="h-4 w-4" :class="loading ? 'animate-spin' : ''" /></UiButton></div>
      <div class="mt-4 grid grid-cols-3 gap-2"><button class="rounded-lg px-2 py-3 text-sm font-bold" :class="tab === 'orders' ? 'bg-primary text-primary-contrast' : 'bg-surface-muted text-muted'" @click="tab='orders'"><ClipboardList class="mx-auto mb-1 h-5 w-5" />Órdenes</button><button class="rounded-lg px-2 py-3 text-sm font-bold" :class="tab === 'quotes' ? 'bg-primary text-primary-contrast' : 'bg-surface-muted text-muted'" @click="tab='quotes'"><FileText class="mx-auto mb-1 h-5 w-5" />Cotizaciones</button><button class="rounded-lg px-2 py-3 text-sm font-bold" :class="tab === 'receivables' ? 'bg-primary text-primary-contrast' : 'bg-surface-muted text-muted'" @click="tab='receivables'"><ReceiptText class="mx-auto mb-1 h-5 w-5" />Por cobrar</button></div>
    </section>

    <template v-if="tab === 'orders'">
      <div class="flex items-center justify-between"><div><strong class="text-text">{{ orders.length }} órdenes</strong><p class="text-sm text-muted">{{ money(receivableTotal) }} pendiente por cobrar</p></div><UiButton @click="resetOrder"><Plus class="h-4 w-4" />Nueva orden</UiButton></div>
      <UiCard v-for="order in orders" :key="order.id" class="space-y-3">
        <div class="flex items-start justify-between gap-3"><div class="min-w-0"><p class="text-xs font-bold text-primary">{{ order.number }}</p><h3 class="truncate font-bold text-text">{{ order.title }}</h3><p class="truncate text-sm text-muted">{{ order.customer.name }}</p></div><UiStatusBadge :tone="tone(order.status)">{{ order.status }}</UiStatusBadge></div>
        <div class="grid grid-cols-3 divide-x divide-line rounded-lg bg-surface-muted py-3 text-center"><div><small class="text-muted">Total</small><strong class="block text-text">{{ money(order.total) }}</strong></div><div><small class="text-muted">Recibido</small><strong class="block text-success">{{ money(order.paid_total) }}</strong></div><div><small class="text-muted">Por cobrar</small><strong class="block" :class="order.balance ? 'text-warning' : 'text-success'">{{ money(order.balance) }}</strong></div></div>
        <div class="flex flex-wrap gap-2"><UiButton v-if="order.balance > 0 && order.status !== 'cancelled'" size="sm" @click="openPayment(order)"><Banknote class="h-4 w-4" />Cobrar</UiButton><UiButton v-if="order.status === 'open'" size="sm" variant="secondary" @click="setOrderStatus(order,'in_progress')">Iniciar</UiButton><UiButton v-if="order.status === 'in_progress'" size="sm" variant="secondary" @click="setOrderStatus(order,'ready')">Marcar lista</UiButton><UiButton v-if="order.status === 'ready'" size="sm" variant="secondary" @click="setOrderStatus(order,'delivered')">Entregar</UiButton><a v-if="order.status !== 'cancelled' && order.billing.status !== 'invoiced'" :href="invoiceHref(order)" class="inline-flex h-9 items-center gap-2 rounded-lg border border-line px-3 text-sm font-semibold text-text"><FileCheck2 class="h-4 w-4" />Facturar</a><UiButton v-if="order.status !== 'cancelled'" size="sm" variant="ghost" class="text-danger" @click="openCancel(order)">Cancelar</UiButton></div>
      </UiCard>
      <p v-if="!orders.length" class="rounded-xl border border-dashed border-line p-10 text-center text-sm text-muted">Todavía no hay órdenes comerciales.</p>
    </template>

    <template v-else-if="tab === 'quotes'">
      <div class="flex items-center justify-between"><strong class="text-text">{{ quotations.length }} cotizaciones</strong><UiButton @click="resetQuote"><Plus class="h-4 w-4" />Nueva cotización</UiButton></div>
      <UiCard v-for="quote in quotations" :key="quote.id" class="space-y-3"><div class="flex items-start justify-between gap-3"><div><p class="text-xs font-bold text-primary">{{ quote.number }}</p><h3 class="font-bold text-text">{{ quote.title }}</h3><p class="text-sm text-muted">{{ quote.customer.name }}</p></div><UiStatusBadge :tone="tone(quote.status)">{{ quote.status }}</UiStatusBadge></div><div class="flex items-end justify-between rounded-lg bg-surface-muted p-3"><div><small class="text-muted">Total cotizado</small><strong class="block text-xl text-text">{{ money(quote.total) }}</strong></div><div class="text-right"><small class="text-muted">Anticipo sugerido</small><strong class="block text-text">{{ money(quote.requested_deposit) }}</strong></div></div><div class="flex flex-wrap gap-2"><UiButton v-if="quote.status === 'draft'" size="sm" variant="secondary" @click="setQuoteStatus(quote,'sent')">Marcar enviada</UiButton><UiButton v-if="['draft','sent'].includes(quote.status)" size="sm" variant="secondary" @click="setQuoteStatus(quote,'accepted')">Aceptar</UiButton><UiButton v-if="['sent','accepted'].includes(quote.status)" size="sm" @click="openConvert(quote)">Convertir en orden</UiButton></div></UiCard>
    </template>

    <template v-else>
      <UiCard class="bg-primary-soft"><p class="text-sm text-muted">Cuentas por cobrar activas</p><p class="mt-1 text-3xl font-black text-text">{{ money(receivableTotal) }}</p><p class="text-sm text-muted">{{ receivables.filter(item => ['open','partial'].includes(item.status)).length }} cuentas pendientes</p></UiCard>
      <UiCard v-for="account in receivables" :key="account.id"><div class="flex items-start justify-between gap-3"><div><p class="text-xs font-bold text-primary">{{ account.source_number }}</p><strong class="text-text">{{ account.customer.name }}</strong><p class="text-sm text-muted">Recibido {{ money(account.paid_amount) }} de {{ money(account.original_amount) }}</p></div><div class="text-right"><UiStatusBadge :tone="tone(account.status)">{{ account.status }}</UiStatusBadge><strong class="mt-2 block text-lg" :class="account.balance ? 'text-warning' : 'text-success'">{{ money(account.balance) }}</strong></div></div></UiCard>
    </template>

    <UiModalShell :open="modal === 'order'" title="Nueva orden de trabajo" description="El saldo se controlará automáticamente en cuentas por cobrar." @close="modal=null"><div class="space-y-4"><UiInput v-model="orderForm.title" label="Trabajo solicitado" placeholder="Ej. Ventana francesa" /><UiInput v-model="orderForm.customer_name" label="Cliente" /><UiInput v-model="orderForm.customer_phone" label="Teléfono opcional" /><div v-for="(item,index) in orderForm.lines" :key="index" class="rounded-lg border border-line p-3"><div class="flex gap-2"><UiInput v-model="item.description" class="flex-1" label="Descripción" /><button type="button" class="mt-6 text-danger" @click="removeLine('order',index)"><Trash2 class="h-4 w-4" /></button></div><div class="mt-3 grid grid-cols-3 gap-2"><UiInput v-model.number="item.quantity" type="number" label="Cantidad" /><UiInput v-model.number="item.unit_price" type="number" label="Precio" /><UiInput v-model.number="item.discount_amount" type="number" label="Descuento" /></div></div><UiButton variant="ghost" size="sm" @click="addLine('order')"><Plus class="h-4 w-4" />Agregar línea</UiButton><div class="rounded-lg bg-surface-muted p-3 text-right"><small class="text-muted">Total</small><strong class="ml-3 text-xl text-text">{{ money(orderTotal) }}</strong></div><div class="grid grid-cols-2 gap-3"><UiInput v-model.number="orderForm.deposit_amount" type="number" label="Anticipo" /><UiSelect v-model="orderForm.deposit_method" label="Forma" :options="methods" /></div><UiTextarea v-model="orderForm.notes" label="Notas" /></div><template #footer><UiButton variant="ghost" @click="modal=null">Cancelar</UiButton><UiButton :disabled="loading || !orderForm.title || !orderForm.customer_name || orderTotal <= 0" @click="createOrder">Crear orden</UiButton></template></UiModalShell>
    <UiModalShell :open="modal === 'quote'" title="Nueva cotización" description="No genera venta ni cuenta por cobrar hasta convertirse en orden." @close="modal=null"><div class="space-y-4"><UiInput v-model="quoteForm.title" label="Proyecto o trabajo" /><UiInput v-model="quoteForm.customer_name" label="Cliente" /><div v-for="(item,index) in quoteForm.lines" :key="index" class="rounded-lg border border-line p-3"><div class="flex gap-2"><UiInput v-model="item.description" class="flex-1" label="Descripción" /><button type="button" class="mt-6 text-danger" @click="removeLine('quote',index)"><Trash2 class="h-4 w-4" /></button></div><div class="mt-3 grid grid-cols-3 gap-2"><UiInput v-model.number="item.quantity" type="number" label="Cantidad" /><UiInput v-model.number="item.unit_price" type="number" label="Precio" /><UiInput v-model.number="item.discount_amount" type="number" label="Descuento" /></div></div><UiButton variant="ghost" size="sm" @click="addLine('quote')"><Plus class="h-4 w-4" />Agregar línea</UiButton><div class="rounded-lg bg-surface-muted p-3 text-right"><strong class="text-xl text-text">{{ money(quoteTotal) }}</strong></div><div class="grid grid-cols-2 gap-3"><UiInput v-model.number="quoteForm.requested_deposit" type="number" label="Anticipo sugerido" /><UiInput v-model="quoteForm.valid_until" type="date" label="Válida hasta" /></div><UiTextarea v-model="quoteForm.terms" label="Condiciones" /></div><template #footer><UiButton variant="ghost" @click="modal=null">Cancelar</UiButton><UiButton :disabled="loading || !quoteForm.title || !quoteForm.customer_name || quoteTotal <= 0" @click="createQuote">Guardar cotización</UiButton></template></UiModalShell>
    <UiModalShell :open="modal === 'payment'" title="Registrar pago" :description="selectedOrder ? `${selectedOrder.number} · saldo ${money(selectedOrder.balance)}` : ''" @close="modal=null"><div class="space-y-4"><UiInput v-model.number="paymentForm.amount" type="number" label="Monto recibido" /><UiSelect v-model="paymentForm.method" label="Forma de pago" :options="methods" /><UiInput v-model="paymentForm.reference" label="Referencia opcional" /></div><template #footer><UiButton variant="ghost" @click="modal=null">Cancelar</UiButton><UiButton :disabled="loading || paymentForm.amount <= 0" @click="savePayment">Registrar</UiButton></template></UiModalShell>
    <UiModalShell :open="modal === 'cancel'" title="Cancelar orden" description="El saldo por cobrar será anulado y el anticipo no retenido se devolverá." @close="modal=null"><div class="space-y-4"><UiTextarea v-model="cancelForm.reason" label="Motivo" /><UiInput v-model.number="cancelForm.retained_amount" type="number" label="Monto que se retiene" /><UiSelect v-model="cancelForm.method" label="Forma de devolución" :options="methods" /><UiInput v-model="cancelForm.reference" label="Referencia opcional" /></div><template #footer><UiButton variant="ghost" @click="modal=null">Volver</UiButton><UiButton variant="danger" :disabled="loading || !cancelForm.reason" @click="cancelOrder">Cancelar y resolver</UiButton></template></UiModalShell>
    <UiModalShell :open="modal === 'convert'" title="Convertir en orden" :description="selectedQuotation ? `${selectedQuotation.number} · ${money(selectedQuotation.total)}` : ''" @close="modal=null"><div class="space-y-4"><UiInput v-model.number="paymentForm.amount" type="number" label="Anticipo recibido" /><UiSelect v-model="paymentForm.method" label="Forma de pago" :options="methods" /><UiInput v-model="paymentForm.reference" label="Referencia opcional" /></div><template #footer><UiButton variant="ghost" @click="modal=null">Cancelar</UiButton><UiButton :disabled="loading" @click="convertQuote">Crear orden</UiButton></template></UiModalShell>
  </div>
</template>
