server {
    server_name admin.stelfaro.com;

    root /var/www/stelfaro-platform/apps/platform-admin/dist;
    index index.html;

    location ^~ /notifications-api/ {
        rewrite ^/notifications-api/(.*)$ /api/$1 break;

        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME /var/www/stelfaro-notifications/public/index.php;
        fastcgi_param SCRIPT_NAME /index.php;
        fastcgi_param DOCUMENT_ROOT /var/www/stelfaro-notifications/public;
        fastcgi_param REQUEST_URI $uri$is_args$args;
        fastcgi_param QUERY_STRING $query_string;
        fastcgi_param HTTP_HOST $host;
        fastcgi_param HTTPS on;
        fastcgi_pass unix:/run/php/php8.3-fpm.sock;
    }

    location /assets/ {
        try_files $uri =404;
        access_log off;
        expires 30d;
        add_header Cache-Control "public, immutable";
    }

    location / {
        try_files $uri $uri/ /index.html;
    }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/admin.stelfaro.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/admin.stelfaro.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}
server {
    if ($host = admin.stelfaro.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    server_name admin.stelfaro.com;

    listen 80;
    return 404; # managed by Certbot


}
