<script setup lang="ts">
import { computed, onMounted, ref } from 'vue';
import QRCode from 'qrcode';
import { Camera, KeyRound, MessageCircle, Printer, RotateCcw } from 'lucide-vue-next';
import { UiButton, UiCard } from '@stelfaro/ui';
import type { WorkshopOrder, WorkshopOrderPhoto } from '@stelfaro/api-client';
import WorkshopPhotoGallery from './WorkshopPhotoGallery.vue';
import { workshopWhatsAppUrl } from './workshopWhatsApp';

const props = defineProps<{ order: WorkshopOrder; photos: WorkshopOrderPhoto[]; photoLoading?: boolean; photoUrl?: string; expiresAt?: string; printing?: boolean }>();
defineEmits<{ reset: []; refreshPhotos: []; print: [] }>();
const qr = ref('');
const whatsappUrl = computed(() => workshopWhatsAppUrl(props.order));
onMounted(async () => { if (props.photoUrl) qr.value = await QRCode.toDataURL(props.photoUrl, { width: 280, margin: 1, errorCorrectionLevel: 'M' }); });
</script>
<template><UiCard class="w-full overflow-hidden p-6 sm:p-8"><div class="text-center"><div class="mx-auto grid h-14 w-14 place-items-center rounded-full bg-success-soft"><Camera class="h-7 w-7 text-success" /></div><h2 class="mt-4 text-2xl font-bold text-text">{{ order.ticket }} registrada</h2><p class="mt-2 text-sm text-muted">El equipo quedó listo para agregar fotografías y entregar la constancia al cliente.</p></div><div class="mt-7 grid gap-6 lg:grid-cols-[320px_1fr]"><div class="rounded-lg border border-line bg-white p-4 text-center"><img v-if="qr" :src="qr" class="mx-auto h-64 w-64" alt="QR temporal para subir fotos"><p v-if="expiresAt" class="mt-2 text-xs text-slate-500">QR válido hasta {{ new Date(expiresAt).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'}) }}</p><p v-else class="py-20 text-sm text-slate-500">No fue posible generar el QR. La orden sí quedó registrada.</p></div><div class="grid content-start gap-3"><a v-if="photoUrl" :href="photoUrl" target="_blank" rel="noopener"><UiButton class="w-full justify-start"><Camera class="mr-2 h-5 w-5" />Abrir carga de fotos</UiButton></a><a v-if="whatsappUrl" :href="whatsappUrl" target="_blank" rel="noopener"><UiButton class="w-full justify-start" variant="success"><MessageCircle class="mr-2 h-5 w-5" />Enviar por WhatsApp</UiButton></a><UiButton class="w-full justify-start" variant="secondary" :disabled="printing" @click="$emit('print')"><Printer class="mr-2 h-5 w-5" />{{ printing ? 'Preparando impresión…' : 'Imprimir ticket' }}</UiButton><p v-if="!whatsappUrl" class="rounded-md bg-warning-soft px-3 py-2 text-sm text-warning">El cliente no tiene teléfono para abrir WhatsApp.</p><div v-if="order.device_access" class="flex items-center gap-3 rounded-md border border-warning bg-warning-soft p-4"><KeyRound class="h-5 w-5 shrink-0 text-warning" /><div><p class="text-xs font-semibold uppercase tracking-wide text-warning">PIN móvil del taller</p><p class="mt-1 font-mono text-xl font-black tracking-[0.2em] text-text">{{ order.device_access.pin }}</p></div></div><div class="mt-2 rounded-md border border-line bg-surface-muted p-4 text-sm"><p class="font-semibold text-text">{{ order.customer.name }}</p><p class="mt-1 text-muted">{{ order.device.brand }} {{ order.device.model }} · {{ order.ticket }}</p></div><UiButton class="mt-2 w-full justify-start" variant="ghost" @click="$emit('reset')"><RotateCcw class="mr-2 h-5 w-5" />Registrar otro equipo</UiButton></div></div><WorkshopPhotoGallery :photos="photos" :loading="photoLoading" @refresh="$emit('refreshPhotos')" /></UiCard></template>
